# Generated by Django 6.0.4 on 2026-05-07 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioTeste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField()),
                ('modelo', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=10)),
                ('agua', models.CharField(max_length=10)),
                ('oleo', models.CharField(max_length=10)),
                ('combustivel', models.CharField(max_length=10)),
                ('km', models.IntegerField()),
                ('foto_frente', models.ImageField(blank=True, null=True, upload_to='checklists/')),
                ('foto_traseira', models.ImageField(blank=True, null=True, upload_to='checklists/')),
                ('foto_motorista', models.ImageField(blank=True, null=True, upload_to='checklists/')),
                ('foto_passageiro', models.ImageField(blank=True, null=True, upload_to='checklists/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Motorista')),
            ],
        ),
    ]
