# Generated by Django 6.0.4 on 2026-05-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistVeicular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
