# Generated by Django 6.0.4 on 2026-05-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_checklist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioteste',
            name='avaria_detalhes',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='usuarioteste',
            name='foto_avaria',
            field=models.ImageField(blank=True, null=True, upload_to='checklists/avarias/'),
        ),
    ]
