# Generated by Django 6.0.4 on 2026-05-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_checklist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarioteste',
            old_name='nome_usuario',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='usuarioteste',
            name='senha',
        ),
        migrations.AddField(
            model_name='usuarioteste',
            name='km',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarioteste',
            name='matricula',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
