# Generated by Django 6.0.4 on 2026-05-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_checklist', '0002_rename_nome_usuario_usuarioteste_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioteste',
            name='agua',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarioteste',
            name='combustivel',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarioteste',
            name='modelo',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarioteste',
            name='oleo',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarioteste',
            name='placa',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
